name: flutter_tencent_captcha
description: 适用于 Flutter 的腾讯云验证码插件
version: 0.1.3
homepage: https://github.com/leanflutter/flutter_tencent_captcha

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.leanflutter.plugins.flutter_tencent_captcha
        pluginClass: FlutterTencentCaptchaPlugin
      ios:
        pluginClass: FlutterTencentCaptchaPlugin

  assets:
    - assets/captcha.html
